// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cumbzeoueqbpxrlpqsxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1bWJ6ZW91ZXFicHhybHBxc3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzgxMjYsImV4cCI6MjA3NDU1NDEyNn0.wOaVYkOrQHkl89_Z_Eeynal86wFopt2fI2A7Ba8tEM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});